FIELD_RULES: dict[str, list[str]] = {
    "data_analyst": [
        "python", "sql", "tableau", "power bi", "powerbi",
        "excel", "analyse de données", "analyse de donnees",
        "data visualization", "visualisation de données", "dataviz",
        "etl", "statistiques", "statistics", "big data",
        "data analysis", "data analyst", "analyste de données",
    ],
    "ai_ml": [
        "machine learning", "ml", "deep learning", "dl",
        "tensorflow", "tf", "pytorch", "nlp",
        "natural language processing", "computer vision",
        "vision par ordinateur", "intelligence artificielle",
        "artificial intelligence", "ia", "ai",
        "réseaux de neurones", "neural networks",
        "data scientist", "data science",
    ],
    "web_dev": [
        "react", "react.js", "reactjs", "angular", "angular.js",
        "angularjs", "vue", "vue.js", "vuejs",
        "javascript", "js", "typescript", "ts",
        "php", "node.js", "nodejs", "node",
        "django", "full stack", "fullstack",
        "développeur web", "developpeur web",
        "web developer", "frontend", "front-end",
        "backend", "back-end", "html", "css",
    ],
    "it": [
        "réseau", "reseau", "network", "système", "systeme",
        "cybersécurité", "cybersecurite", "cybersecurity",
        "cloud", "devops", "linux",
        "administration système", "administration systeme",
        "system administrator", "it support", "support technique",
        "infrastructure", "it", "informatique",
    ],
}
